Enhance error handling in LOLRMM repository retrieval step

diff --git a/.github/workflows/lolrmm_wikijm-to-s1pq-converter-create_markdown.yml b/.github/workflows/lolrmm_wikijm-to-s1pq-converter-create_markdown.yml
--- a/.github/workflows/lolrmm_wikijm-to-s1pq-converter-create_markdown.yml
+++ b/.github/workflows/lolrmm_wikijm-to-s1pq-converter-create_markdown.yml
@@ -33,13 +33,25 @@ jobs:
         run: |
           sigma plugin install sentinelone-pq
         
-      - name: Get LOLRMM repository
-        run: |
-          mkdir -p "datasources/${{ env.SIGMACATEGORY }}"
-          wget -O "datasources/${{ env.SIGMACATEGORY }}/${{ env.SIGMACATEGORY }}.zip" "${{ env.SOURCEURL }}"
-          unzip -o "datasources/${{ env.SIGMACATEGORY }}/${{ env.SIGMACATEGORY }}.zip" "LOLRMM-main/yaml/*" -d "datasources/${{ env.SIGMACATEGORY }}"
-          mv "datasources/${{ env.SIGMACATEGORY }}/LOLRMM-main/yaml/*.yaml" "datasources/${{ env.SIGMACATEGORY }}/"
-          find "datasources/${{ env.SIGMACATEGORY }}/"" -type f ! -name '*.yaml' -exec rm -f {} + && find "datasources/${{ env.SIGMACATEGORY }}/" -type d -empty -delete
+          - name: Get LOLRMM repository
+          run: |
+            mkdir -p "datasources/${{ env.SIGMACATEGORY }}"
+            wget -O "datasources/${{ env.SIGMACATEGORY }}/${{ env.SIGMACATEGORY }}.zip" "${{ env.SOURCEURL }}"
+            unzip -o "datasources/${{ env.SIGMACATEGORY }}/${{ env.SIGMACATEGORY }}.zip" -d "datasources/${{ env.SIGMACATEGORY }}"
+            
+            # Verify if the directory and .yaml files exist
+            if [ ! -d "datasources/${{ env.SIGMACATEGORY }}/LOLRMM-main/yaml/" ]; then
+              echo "Error: Directory 'LOLRMM-main/yaml/' does not exist in the archive."
+              exit 1
+            fi
+            
+            if [ -z "$(ls -1 datasources/${{ env.SIGMACATEGORY }}/LOLRMM-main/yaml/*.yaml 2>/dev/null)" ]; then
+              echo "Error: No .yaml files found in the 'LOLRMM-main/yaml/' directory."
+              exit 1
+            fi
+            
+            mv "datasources/${{ env.SIGMACATEGORY }}/LOLRMM-main/yaml/"*.yaml "datasources/${{ env.SIGMACATEGORY }}/"
+            find "datasources/${{ env.SIGMACATEGORY }}/" -type f ! -name '*.yaml' -exec rm -f {} + && find "datasources/${{ env.SIGMACATEGORY }}/" -type d -empty -delete
 
       - name: Create destination folder "results/${{ env.SIGMACATEGORY }}-${{ env.PLATFORM }}"
         run: |
